### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [StanlyHardy/FlareView#2]
I'd be cool to also add CocoaPods support. I've done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by StanlyHardy** [comment]
enhancement

**Comment by StanlyHardy** [comment]
The project has been enhanced. The Support for CocoaPods has been provided.
